//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mentor_Matchine.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mentor_MatchineEntities : DbContext
    {
        public Mentor_MatchineEntities()
            : base("name=Mentor_MatchineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lang> Lang { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Mentee> Mentee { get; set; }
        public virtual DbSet<MenteeLanguage> MenteeLanguage { get; set; }
        public virtual DbSet<Mentor> Mentor { get; set; }
        public virtual DbSet<MentorLanguage> MentorLanguage { get; set; }
        public virtual DbSet<MentorPreferences> MentorPreferences { get; set; }
        public virtual DbSet<Nationality> Nationality { get; set; }
    }
}
