//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mentor_Matchine.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentorLanguage
    {
        public int MentorL_ID { get; set; }
        public Nullable<int> MentorID { get; set; }
        public Nullable<int> LanguageID { get; set; }
    
        public virtual Lang Lang { get; set; }
        public virtual Mentor Mentor { get; set; }
    }
}
